### ISSUE TITLE
iterator not working in table?

### ISSUE THREAD

**Issue by mrbm** [alpine-collective/alpine-magic-helpers#125]
https://codepen.io/storegear/pen/KKaJwmR

So...day 4 on this on why iterator kills everything and now the variable seems to be it doesn't work when in a loop when in a TABLE. Take out the table mark up and it works.

@KevinBatdorf @SimoTod

**Comment by SimoTod** [comment]
Sorry if i insist: the x-data MUST be on the first child of your template tag, in this case tr.
It's because this way to access the variable is an hack and exploits the way Alpine saves the current loop element to optimise the next refreshes.
Keep in mind that it's an internal API, It's not documented anywhere and it might also change in the future.

**Comment by SimoTod** [comment]
Closing since it's not a bug and the question is not related to the helpers.
Feel free to open a discussion on the Alpine repo or this one if you have further questions.
