### ISSUE TITLE
Unsupported $scroll target

### ISSUE THREAD

**Issue by OGhawsi** [alpine-collective/alpine-magic-helpers#54]
This is really a very helpful package and I am trying to use it inside laravel app. 
I have imported both `import 'alpine-magic-helpers'; import 'alpinejs';` 
I am trying to use the $scroll helper and I have tried both $refs and using #id but when I click on the button to scroll to that specific  section, It is not working and it shows  the following error in the console. 
`
Uncaught (in promise) Error: Unsupported $scroll target: 
    at Proxy.eval (index.js?d52a:2334)
    at eval (eval at saferEvalNoReturn (alpine.js?df24:1900), <anonymous>:3:21)
    at saferEvalNoReturn (alpine.js?df24:143)
    at Component.evaluateCommandExpression (alpine.js?df24:1720)
    at runListenerHandler (alpine.js?df24:895)
    at HTMLButtonElement.handler (alpine.js?df24:871)
eval @ index.js?d52a:2334
eval @ VM1370:3
saferEvalNoReturn @ alpine.js?df24:143
evaluateCommandExpression @ alpine.js?df24:1720
runListenerHandler @ alpine.js?df24:895
handler @ alpine.js?df24:871
Promise.then (async)
handler @ alpine.js?df24:872
`

Just as a remider the $scroll(0) is working fine.

Thanks in advance

**Comment by SimoTod** [comment]
https://github.com/alpine-collective/alpine-magic-helpers/issues/52
It could it the same bug reported here. There will be a fix soon, I'll message you to test it when ready.

**Comment by SimoTod** [comment]
@OGhawsi Wnen you have time, could you try <script src="https://cdn.jsdelivr.net/gh/SimoTod/alpine-magic-helpers@bug/scroll-float-values/dist/index.min.js"></script> and let me know if it fixes your bug? 
If everything is okay, we'll tag a patch release soon. Thanks

**Comment by SimoTod** [comment]
We released it so your error may be fixed already. Let us know.

**Comment by OGhawsi** [comment]
Thanks, @SimoTod for your quick fix and response. It is working fine now. 
and I have noticed that the size of my js file increased to 417 KiB from 200 Kib after installing alpine-magic-helpers, and with npm run prod, the js file size is 50 KiB and without this package, it is only 26 KiB. And AlpineJS is known for its small size, so it would be nice if the size of the compiled package is reduced. 
Thanks.

**Comment by SimoTod** [comment]
HI @OGhawsi. thanks for confirming that.

This library adds a bunch of features to enhance the Alpine experience. That comes with a cost, additional KB. 
As you pointed out, in production and with proper minification is currently ~24KB because there is some additional code to support multiple browsers. 

This is unlikely to diminish and it will go up while we add new features but we will try to keep it as small as possible.
If you see a point where you can optimize it further, feel free to send a PR and we'll review and get it merged.

Bear in mind that 24KB is roughly the weight of a low-quality image and about half the size of the sprite that Google uses in its search engine (https://ssl.gstatic.com/gb/images/p1_799229b0.png). Over the network, when using gzip is about 8KB so I wouldn't define it as "huge".

If you are compiling your bundle and you don't use certain features, you can strip them from your build since all the helpers are exported separately (see https://github.com/alpine-collective/alpine-magic-helpers/blob/master/src/index.js#L9).
Fetch alone for example is 13KB so if you don't use it, you'll save more than half the weight.

I hope it helps.
