### ISSUE TITLE
Add `defer` attribute to `script` tags under Installation header in README

### ISSUE THREAD

**Issue by dane-skipper** [alpine-collective/alpine-magic-helpers#71]
The demonstrated Install instructions on the AlpineJS repository use the `defer` attribute on the `script` tag. Perhaps the README and the Installation `script` tag demonstrations here should be updated accordingly as well?

NB: I have not read the source code for these helpers, so I don't know if there's a reason for the helpers to block the parsing of the page while loading and then executing. My assumption is that since these helpers are dependent upon the base Alpine framework, their utility comes following the load and execution of the base framework.

**Comment by SimoTod** [comment]
There's no reason. It's up to the developer, it should match the Alpine script and the helper script should come first. We are happy to accept PRs to improve the readme. 

To add more details, One can decide to have defer or to put both scripts at the botton of the page or both without defer. They are all valid combinations.

We didn't describe that in the readme because it might confuse people if it's too verbose. 

Just as a reminder, defer is not async. It doesn't block the download and parsing of the rest of the page but it's still blocking the DOM Ready event.

**Comment by KevinBatdorf** [comment]
Yeah, this is tricky because the helpers _need_ to load before Alpine and adding `defer` can sometimes cause race conditions of script loading. I believe this is because when `defer` is added, browsers don't guarantee the order they will load in the script, and instead use other factors like file size. 

My thoughts on this are that if you really need to defer the script you should probably use a bundler do combine Alpine with the helpers you need and defer the entire build file.

**Comment by dane-skipper** [comment]
Oh interesting -- thank you for the context and the tip!

**Comment by KevinBatdorf** [comment]
@dane-skipper I updated that reply a bit for more clarity/context (probably didn't show in your email). My original reply was probably more anecdotal based on observations in Discord than anything else. 

The readme could probably use a bit more clarity as well on the issue. I'll try to find a responsible way to add something to the docs.
