### ISSUE TITLE
Accessing the $parent properties and functions from the child init() no longer works in 1.0.0

### ISSUE THREAD

**Issue by pomartel** [alpine-collective/alpine-magic-helpers#95]
Accessing properties and functions from `$parent` in the child `init()` function works in version 0.6.0. It no longer works in 1.0.0 so this might be a regression.

0.6.0 (works) : https://codepen.io/pomartel/pen/jOVaZKX
1.0.0 (broken): https://codepen.io/pomartel/pen/bGBYLmx

**Comment by SimoTod** [comment]
Hi Pierre, thanks for reporting. The reason is that, when the child runs x-init, the parent hasn't fully initiated yet. 0.x was using an hack to evaluate the parent x-data in the child when the parent component was not ready. The problem with that approach was that it was using a different object under the scene so you couldn't access the magic properties of the parent component.
1.0 defers the evaluation of those properties until the parent is ready but on x-init, they will be considered as empty string.
I'll see what we can do, in the meantime, you can use a timeout to make it work: https://codepen.io/SimoTod/pen/RwojMGJ

**Comment by pomartel** [comment]
Thanks @SimoTod! a `setTimeout` indeed does the trick. I can live with that. I see you did not put a delay for your timeout. Will that always work? Or should I put a 10ms delay or more?

**Comment by SimoTod** [comment]
It will always work, requestAnimationFrame would work as well. It just needs to release the main thread of execution so the parent can carry over. Js is single threaded, setTimeout is just a close match. By the time it gets the control back, parent will be fully available.
I'll keep you posted if we can make it work again, keeping the enhanced functionalities. If we can't do anything, we'll need to mention it in the doc for other developers.

**Comment by SimoTod** [comment]
@pomartel $nextTick works as well. At the moment, we can't fix it without breaking other features so I just added a special section in the readme to add clarity about the known issue.

**Comment by pomartel** [comment]
Great, thanks for your help!
